"""add currency_pair_snapshot book_depth_snapshot candle_stick_snapshot

Revision ID: 3edac122b283
Revises: b9d357a15550
Create Date: 2026-02-28 23:55:47.944913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3edac122b283'
down_revision: Union[str, Sequence[str], None] = 'b9d357a15550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_depth_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange_symbol', sa.String(), nullable=True),
    sa.Column('last_update_id', sa.Text(), nullable=True),
    sa.Column('utc', sa.Float(), nullable=True),
    sa.Column('bids_asks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('align_to_minutes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_depth_snapshot_exchange_kind', 'book_depth_snapshot', ['exchange_id', 'kind'], unique=False)
    op.create_index('ix_book_depth_snapshot_symbol', 'book_depth_snapshot', ['exchange_id', 'kind', 'symbol'], unique=False)
    op.create_table('candle_stick_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('span_in_minutes', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('utc_open_time', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('coin_volume', sa.Float(), nullable=False),
    sa.Column('usd_volume', sa.Float(), nullable=True),
    sa.Column('align_to_minutes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candle_stick_snapshot_exchange_kind', 'candle_stick_snapshot', ['exchange_id', 'kind'], unique=False)
    op.create_index('ix_candle_stick_snapshot_symbol', 'candle_stick_snapshot', ['exchange_id', 'kind', 'symbol'], unique=False)
    op.create_table('currency_pair_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('utc', sa.Float(), nullable=True),
    sa.Column('align_to_minutes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_currency_pair_snapshot_exchange_kind', 'currency_pair_snapshot', ['exchange_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_pair_snapshot_exchange_kind', table_name='currency_pair_snapshot')
    op.drop_table('currency_pair_snapshot')
    op.drop_index('ix_candle_stick_snapshot_symbol', table_name='candle_stick_snapshot')
    op.drop_index('ix_candle_stick_snapshot_exchange_kind', table_name='candle_stick_snapshot')
    op.drop_table('candle_stick_snapshot')
    op.drop_index('ix_book_depth_snapshot_symbol', table_name='book_depth_snapshot')
    op.drop_index('ix_book_depth_snapshot_exchange_kind', table_name='book_depth_snapshot')
    op.drop_table('book_depth_snapshot')
    # ### end Alembic commands ###
