"""add token crawler_job crawler_iteration

Revision ID: b9d357a15550
Revises: 08d76073eace
Create Date: 2026-02-27 23:12:49.276759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d357a15550'
down_revision: Union[str, Sequence[str], None] = '08d76073eace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('connector', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stop', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawler_job_exchange_connector', 'crawler_job', ['exchange', 'connector'], unique=False)
    op.create_index('ix_crawler_job_start', 'crawler_job', ['start'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'source', name='uq_token_symbol_source')
    )
    op.create_table('crawler_iteration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawler_job_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stop', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency_pair', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('book_depth', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('klines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funding_rate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_funding_rate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funding_rate_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['crawler_job_id'], ['crawler_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawler_iteration_crawler_job_id', 'crawler_iteration', ['crawler_job_id'], unique=False)
    op.create_index('ix_crawler_iteration_job_token', 'crawler_iteration', ['crawler_job_id', 'token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crawler_iteration_job_token', table_name='crawler_iteration')
    op.drop_index('ix_crawler_iteration_crawler_job_id', table_name='crawler_iteration')
    op.drop_table('crawler_iteration')
    op.drop_table('token')
    op.drop_index('ix_crawler_job_start', table_name='crawler_job')
    op.drop_index('ix_crawler_job_exchange_connector', table_name='crawler_job')
    op.drop_table('crawler_job')
    # ### end Alembic commands ###
