# Generated by Django 4.1.7 on 2023-07-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(db_index=True, max_length=128)),
                ('secrets', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential', to='core.session')),
            ],
        ),
    ]
