# Generated by Django 4.1.7 on 2023-07-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccountcredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountcredential',
            name='session',
        ),
    ]
