# Generated by Django 4.1.7 on 2023-07-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_useraccountcredential_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.useraccountcredential'),
        ),
    ]
