# Generated by Django 4.1.7 on 2023-07-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_credential'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccountcredential',
            unique_together={('engine', 'account')},
        ),
    ]
