# Generated by Django 4.1.7 on 2023-07-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_useraccountcredential_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
