# Generated by Django 4.1.7 on 2023-08-02 22:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_useraccount_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PAdvertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('min_qty', models.FloatField()),
                ('max_qty', models.FloatField()),
                ('pay_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), size=None)),
                ('epoch', models.IntegerField(db_index=True)),
                ('utc', models.FloatField(db_index=True)),
                ('extra', models.JSONField(null=True)),
                ('data_hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='P2PAdvertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.CharField(db_index=True, max_length=24)),
                ('uid', models.CharField(db_index=True, max_length=64)),
                ('nick', models.CharField(db_index=True, max_length=64)),
                ('rating', models.FloatField(db_index=True, null=True)),
                ('finish_rate', models.FloatField(db_index=True, null=True)),
                ('trades_month', models.IntegerField(db_index=True, null=True)),
                ('trades_total', models.IntegerField(db_index=True, null=True)),
                ('hash', models.TextField()),
                ('extra', models.JSONField()),
            ],
        ),
    ]
