# Generated by Django 4.1.7 on 2023-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_p2padvertinfo_p2padvertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2padvertinfo',
            name='epoch',
            field=models.FloatField(db_index=True),
        ),
    ]
