# Generated by Django 4.1.7 on 2023-08-03 22:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_p2padvertinfo_epoch'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PAdvertPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='p2padvertinfo',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.p2padvertiser'),
        ),
        migrations.AddField(
            model_name='p2padvertinfo',
            name='duplicate_epochs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
