# Generated by Django 4.1.7 on 2023-08-03 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_p2padvertposition_p2padvertinfo_advertiser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertposition',
            name='adv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.p2padvertinfo'),
        ),
        migrations.AddField(
            model_name='p2padvertposition',
            name='epoch',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2padvertposition',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
