# Generated by Django 4.1.7 on 2023-08-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_p2padvertposition_adv_p2padvertposition_epoch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2padvertinfo',
            name='utc',
        ),
    ]
