# Generated by Django 4.1.7 on 2023-08-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_p2padvertinfo_utc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='p2padvertiser',
            unique_together={('exchange_code', 'uid')},
        ),
    ]
