# Generated by Django 4.1.7 on 2023-08-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_p2padvertiser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2padvertposition',
            name='adv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.p2padvertinfo'),
        ),
    ]
