# Generated by Django 4.1.7 on 2023-08-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_p2padvertposition_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2padvertinfo',
            name='data_hash',
            field=models.TextField(db_index=True),
        ),
    ]
