# Generated by Django 4.1.7 on 2023-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_p2padvertinfo_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertinfo',
            name='fiat',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
