# Generated by Django 4.1.7 on 2023-08-18 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_p2padvertinfo_fiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertinfo',
            name='exchange_code',
            field=models.CharField(db_index=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='p2padvertinfo',
            name='pay_methods_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='p2padvertinfo',
            name='pay_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), db_index=True, size=None),
        ),
    ]
