# Generated by Django 4.1.7 on 2023-08-24 21:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_p2padvertinfo_exchange_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2padvertinfo',
            name='duplicate_epochs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
