# Generated by Django 4.1.7 on 2023-08-28 19:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_p2padvertinfo_duplicate_epochs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2padvertinfo',
            name='pay_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), db_index=True, default=list, size=None),
        ),
    ]
