# Generated by Django 4.1.7 on 2023-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_p2padvertinfo_pay_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertinfo',
            name='side',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
