# Generated by Django 4.1.7 on 2023-09-11 22:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_p2padvertinfo_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertposition',
            name='created',
            field=models.FloatField(default=core.utils.utc_now_float),
        ),
    ]
