# Generated by Django 4.1.7 on 2023-09-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_p2padvertposition_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertinfo',
            name='token',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
