# Generated by Django 4.1.7 on 2023-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_p2padvertinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertposition',
            name='exchange_code',
            field=models.CharField(db_index=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='p2padvertposition',
            name='fiat',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='p2padvertposition',
            name='side',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='p2padvertposition',
            name='token',
            field=models.CharField(db_index=True, max_length=16, null=True),
        ),
    ]
