# Generated by Django 4.1.7 on 2023-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_p2padvertposition_exchange_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.FloatField(db_index=True)),
                ('exchange_code', models.CharField(db_index=True, max_length=24, null=True)),
                ('side', models.CharField(db_index=True, max_length=16, null=True)),
                ('token', models.CharField(db_index=True, max_length=16, null=True)),
            ],
            options={
                'unique_together': {('epoch', 'exchange_code', 'side', 'token')},
            },
        ),
    ]
