# Generated by Django 4.1.7 on 2023-10-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_p2pepoch_fiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pepoch',
            name='errors',
            field=models.JSONField(null=True),
        ),
    ]
