# Generated by Django 4.1.7 on 2023-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_p2pepoch_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PTradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.FloatField(db_index=True)),
                ('exchange_code', models.CharField(db_index=True, max_length=24, null=True)),
                ('side', models.CharField(db_index=True, max_length=16, null=True)),
                ('token', models.CharField(db_index=True, max_length=16, null=True)),
                ('fiat', models.CharField(db_index=True, max_length=10, null=True)),
                ('advert_uid', models.CharField(db_index=True, max_length=128)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('extra', models.JSONField(null=True)),
            ],
        ),
    ]
