# Generated by Django 4.1.7 on 2023-10-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_p2ptradeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptradeevent',
            name='position',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
