# Generated by Django 4.1.7 on 2023-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_p2ptradeevent_pay_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptradeevent',
            name='advertiser_uid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
