# Generated by Django 4.1.7 on 2023-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_p2ptradeevent_advertiser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptradeevent',
            name='counterparty_position',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
