# Generated by Django 4.1.7 on 2023-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_p2ptradeevent_counterparty_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCollectorsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.CharField(db_index=True, max_length=32)),
                ('storage', models.JSONField()),
                ('updated', models.FloatField()),
            ],
        ),
    ]
