# Generated by Django 4.1.7 on 2023-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_exchangecollectorsstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptradeevent',
            name='uid',
            field=models.CharField(max_length=48, null=True, unique=True),
        ),
    ]
