# Generated by Django 4.1.7 on 2023-10-20 16:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_p2ptradeevent_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCollectorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128, null=True)),
                ('timestamp', models.FloatField(db_index=True)),
                ('data', models.JSONField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), db_index=True, default=list, size=None)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exchangecollectorsstorage')),
            ],
        ),
    ]
