# Generated by Django 4.1.7 on 2023-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_exchangecollectoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertinfo',
            name='quantity_fiat',
            field=models.FloatField(null=True),
        ),
    ]
