# Generated by Django 4.1.7 on 2023-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_p2padvertinfo_quantity_fiat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecollectoritem',
            name='exchange',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
