# Generated by Django 4.1.7 on 2023-10-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_exchangecollectoritem_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertiser',
            name='verified_merchant',
            field=models.BooleanField(null=True),
        ),
    ]
