# Generated by Django 4.1.7 on 2023-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_p2padvertiser_verified_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2padvertiser',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
