# Generated by Django 4.1.7 on 2023-11-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_p2padvertiser_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptradeevent',
            name='forex_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='p2ptradeevent',
            name='usdt_price',
            field=models.FloatField(null=True),
        ),
    ]
