# Generated by Django 4.1.7 on 2024-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_spreadevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=24)),
                ('utc', models.FloatField(db_index=True)),
                ('details', models.JSONField()),
            ],
        ),
    ]
